# Generated by Django 4.1.2 on 2022-11-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
