# Generated by Django 4.1.2 on 2022-12-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
