# Generated by Django 4.1.2 on 2022-11-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_pincode_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_methodd',
            new_name='payment_method',
        ),
    ]
