# Generated by Django 4.1.2 on 2022-11-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_address_line_1_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercar',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Acccepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=10),
        ),
    ]
